### PR TITLE
Web form to collect payments

### PR DESCRIPTION
**Pull request by Ajaxy**
Dashboard screenshot (isn't there any staging/showcase environment btw?): 
JSAPI repo (you guys are invited): https://github.com/Ajaxy/monei-jsapi
Showcase: http://monei-jsapi.s3-website.eu-central-1.amazonaws.com/

There is a problem now, that PayOn requires adding `<script>` for each form and it conflicts with existing enhanced forms. So we should think about how to handle multiple forms.

And also, I didn't know where to put backend proxy, so I just harcoded credentials here: https://github.com/Ajaxy/monei-jsapi/blob/master/src/widget/tools/checkout.js#L7

### CODE REVIEW

**Comment by alexandresaiz** [comment]
@Ajaxy comments:

1.- The web form is on per SubAccount basis, not on per user basis so it should be removed from header and should be placed within SubAccount tab/s.

2.- Coordinate with @davidgf so he can create/host the widget.js at: static.monei.net

3.- Make sure you show the currency which the SubAccount has been created for.

4.- Callbak is a geek term. Can we use something more semantic and easier/kindergarten towards instead?

5.- Can we somehow add a text which reads: Test it! And on click the user can see a popup with the form?

******************
FORM BUILT: (http://monei-jsapi.s3-website.eu-central-1.amazonaws.com/)

see:
https://www.dropbox.com/s/vzbr6a1ymhfmvyz/Captura%20de%20pantalla%202016-12-18%2018.49.06.png?dl=0
https://shop.stripe.com/
https://billigpoker.dk/

1.- We don't want to bother the user by asking which brand his credit card is

2.- We need to ask for email as this is MONEI's unique way of identifiying a customer.

3.- We don't want to ask for Cad holder details unless merchant / user wants to. (digital products won't require a web form/widget with any personal details but email address.

4.- We should show the amount to be paid on the CTA button as:
https://www.dropbox.com/s/66u6offgcyr5c9v/Captura%20de%20pantalla%202016-12-18%2018.53.16.png?dl=0

currency of the SubAccount should be shown there.

5.- Can we make the overall look 'n feel a bit more modern like Stripe or PayLike ? 
https://billigpoker.dk/#

**Comment by Ajaxy** [comment]
>  We don't want to ask for Cad holder details unless merchant / user wants to. (digital products won't require a web form/widget with any personal details but email address.
Does it mean we need some additional fields while building HTML for widget in a dashboard?

**Comment by alexandresaiz** [comment]
What would you suggest. Allowing user to add extra fields would give extra value to the widget

**Comment by Ajaxy** [comment]
I think it's possible. I'll just need to test if PayOn allows empty cardholder field.

**Pull request merged**
